---
title: "general"
author: "Cintia Anna Nagy"
date: "`r Sys.Date()`"
output: html_document
---

# import packages

```{r message = FALSE}
library(tidyverse)
library(stats)
library(rstatix)
```

# import data

```{r message = FALSE}
study1 <- read_delim("processed_data/study_1/data_study_1_general.csv", delim = ';')
study2 <- read_delim("processed_data/study_2/data_study_2_general.csv", delim = ';')
study2_cog_tasks <- read_csv("processed_data/study_2/data_study_2_cognitive_tasks.csv")
```

# preprocess data
## Study 1

```{r}
study1 <- study1 %>% 
  mutate(age = as.numeric(age))
  
study1_lowerAQ <- study1 %>% 
  filter(Group == 0)

study1_higherAQ <- study1 %>% 
  filter(Group == 1)
```

## Study 2

```{r}
study2 <- study2 %>% 
  mutate(age = as.numeric(age))

study2_NTP <- study2 %>% 
  filter(Group == 0)

study2_ASD <- study2 %>% 
  filter(Group == 1)
```

# Study 1 
## age

```{r}
mean(study1$age)
sd(study1$age)
```

```{r}
shapiro.test(study1_lowerAQ$age)
shapiro.test(study1_higherAQ$age)
mean(study1_lowerAQ$age)
sd(study1_lowerAQ$age)
mean(study1_higherAQ$age)
sd(study1_higherAQ$age)
wilcox.test(study1_lowerAQ$age, study1_higherAQ$age)
wilcox_effsize(study1, age ~ Group)
```

## sex

```{r}
table(study1$sex)
```


```{r}
study1_sex_table = table(study1$Group, study1$sex)
study1_sex_table
chisq.test(study1_sex_table, correct = FALSE)
```

## cognitive capacity

```{r}
shapiro.test(study1_lowerAQ$digit_span)
shapiro.test(study1_higherAQ$digit_span)
mean(study1_lowerAQ$digit_span)
sd(study1_lowerAQ$digit_span)
mean(study1_higherAQ$digit_span)
sd(study1_higherAQ$digit_span)
wilcox.test(study1_lowerAQ$digit_span, study1_higherAQ$digit_span)
wilcox_effsize(study1, digit_span ~ Group)
```

# Study 2
## age

```{r}
shapiro.test(study2_NTP$age)
shapiro.test(study2_ASD$age)
mean(study2_NTP$age)
sd(study2_NTP$age)
mean(study2_ASD$age)
sd(study2_ASD$age)
wilcox.test(study2_NTP$age, study2_ASD$age)
wilcox_effsize(study2, age ~ Group)
```

## sex

```{r}
study2_sex_table = table(study2$Group, study2$sex)
study2_sex_table
chisq.test(study2_sex_table, correct = FALSE)
```

## cognitive profile

```{r}
study2_cog_tasks <- study2_cog_tasks %>% 
  group_by(Subject) %>% 
  mutate(letter_count = (letter_1_count + letter_2_count)/2,
         semantic_count = (semantic_1_count + semantic_2_count)/2)
  
study2_cog_NTP <- study2_cog_tasks %>% 
  filter(Group == 0)

study2_cog_ASD <- study2_cog_tasks %>% 
  filter(Group == 1)
```

### DSPAN

```{r}
shapiro.test(study2_cog_NTP$dspan)
shapiro.test(study2_cog_ASD$dspan)
mean(study2_cog_NTP$dspan)
sd(study2_cog_NTP$dspan)
mean(study2_cog_ASD$dspan)
sd(study2_cog_ASD$dspan)
t.test(dspan ~ Group, data = study2_cog_tasks, var.equal = TRUE)
cohens_d(study2_cog_tasks, dspan ~ Group)
```

### CSPAN

```{r}
shapiro.test(study2_cog_NTP$cspan)
shapiro.test(study2_cog_ASD$cspan)
mean(study2_cog_NTP$cspan)
sd(study2_cog_NTP$cspan)
mean(study2_cog_ASD$cspan)
sd(study2_cog_ASD$cspan)
t.test(cspan ~ Group, data = study2_cog_tasks, var.equal = TRUE)
cohens_d(study2_cog_tasks, cspan ~ Group)
```

### BCST

```{r}
shapiro.test(study2_cog_NTP$PersErrorP)
shapiro.test(study2_cog_ASD$PersErrorP)
mean(study2_cog_NTP$PersErrorP)
sd(study2_cog_NTP$PersErrorP)
mean(study2_cog_ASD$PersErrorP)
sd(study2_cog_ASD$PersErrorP)
wilcox.test(study2_cog_NTP$PersErrorP, study2_cog_ASD$PersErrorP)
wilcox_effsize(study2_cog_tasks, PersErrorP ~ Group)
```

### GNG

```{r}
shapiro.test(study2_cog_NTP$dprime_s1)
shapiro.test(study2_cog_ASD$dprime_s1)
mean(study2_cog_NTP$dprime_s1)
sd(study2_cog_NTP$dprime_s1)
mean(study2_cog_ASD$dprime_s1)
sd(study2_cog_ASD$dprime_s1)
t.test(dprime_s1 ~ Group, data = study2_cog_tasks, var.equal = TRUE)
cohens_d(study2_cog_tasks, dprime_s1 ~ Group)
```

```{r}
shapiro.test(study2_cog_NTP$dprime_s2)
shapiro.test(study2_cog_ASD$dprime_s2)
mean(study2_cog_NTP$dprime_s2)
sd(study2_cog_NTP$dprime_s2)
mean(study2_cog_ASD$dprime_s2)
sd(study2_cog_ASD$dprime_s2)
wilcox.test(study2_cog_NTP$dprime_s2, study2_cog_ASD$dprime_s2)
wilcox_effsize(study2_cog_tasks, dprime_s2 ~ Group)
```
### Fluency

```{r}
# letter fluency
shapiro.test(study2_cog_NTP$letter_count)
shapiro.test(study2_cog_ASD$letter_count)
mean(study2_cog_NTP$letter_count)
sd(study2_cog_NTP$letter_count)
mean(study2_cog_ASD$letter_count)
sd(study2_cog_ASD$letter_count)
t.test(letter_count ~ Group, data = study2_cog_tasks, var.equal = TRUE)
cohens_d(study2_cog_tasks, letter_count ~ Group)
```

```{r}
# semantic fluency
shapiro.test(study2_cog_NTP$semantic_count)
shapiro.test(study2_cog_ASD$semantic_count)
mean(study2_cog_NTP$semantic_count)
sd(study2_cog_NTP$semantic_count)
mean(study2_cog_ASD$semantic_count)
sd(study2_cog_ASD$semantic_count)
wilcox.test(study2_cog_NTP$semantic_count, study2_cog_ASD$semantic_count)
wilcox_effsize(study2_cog_tasks, semantic_count ~ Group)
```


