---
title: "meta_analysis"
author: "Cintia Anna Nagy"
date: "`r Sys.Date()`"
output: html_document
---
# import packages

```{r message = FALSE}
library(tidyverse)
library(ggplot2)
library(readr)
library(meta)
```

# import data

```{r message = FALSE}
study1_SL <- read_csv("processed_data/study_1/data_study_1_SL_offline_online.csv")
study1_VP <- read_csv("processed_data/study_1/data_study_1_VP_offline_online.csv")
study2_SL <- read_csv("processed_data/study_2/data_study_2_SL_offline_online.csv")
study2_VP <- read_csv("processed_data/study_2/data_study_2_VP_offline_online.csv")
```

# Offline statistical learning in the two studies

```{r}
metadat_SL_off <- data.frame(n.e = c(length(study1_SL$offline_SL[study1_SL$Group == '1']), length(study2_SL$offline_SL[study2_SL$Group == '1'])),
                      mean.e = c(mean(study1_SL$offline_SL[study1_SL$Group == '1']), mean(study2_SL$offline_SL[study2_SL$Group == '1'])),
                      sd.e = c(sd(study1_SL$offline_SL[study1_SL$Group == '1']), sd(study2_SL$offline_SL[study2_SL$Group == '1'])),
                      n.c = c(length(study1_SL$offline_SL[study1_SL$Group == '0']), length(study2_SL$offline_SL[study2_SL$Group == '0'])),
                      mean.c = c(mean(study1_SL$offline_SL[study1_SL$Group == '0']), mean(study2_SL$offline_SL[study2_SL$Group == '0'])),
                      sd.c = c(sd(study1_SL$offline_SL[study1_SL$Group == '0']), sd(study2_SL$offline_SL[study2_SL$Group == '0'])),
                      studlab = c("Study 1", "Study 2")
                      )

m.cont_SL_off <- metacont(n.e = n.e,
                   mean.e = mean.e,
                   sd.e = sd.e,
                   n.c = n.c,
                   mean.c = mean.c,
                   sd.c = sd.c,
                   studlab = studlab,
                   data = metadat_SL_off,
                   sm = "SMD",
                   method.smd = "Hedges",
                   comb.fixed = T,
                   comb.random = F,
                   method.tau = "REML",
                   hakn = TRUE,
                   title = "Offline SL")

summary(m.cont_SL_off)

#png(file = "meta_stat_off.png", width = 3200, height = 2000, res = 300)

forest.meta(m.cont_SL_off,
            label.e = "Higher AQ/ ASD",
            label.c = "Lower AQ/ NTP",
            comb.common = T,
            text.common = "Fixed-effect model",
            print.I2.ci = T,
            print.tau2.ci = T,
            print.Q = T,
            print.pval.Q = T,
            test.overall = T,
            details = T,
            xlim = c(-0.6, 0.6)
            )

dev.off()
```

# Offline visuomotor performance in the two studies

```{r}
metadat_VP_off <- data.frame(n.e = c(length(study1_VP$offline_VP[study1_VP$Group == '1']), length(study2_VP$offline_VP[study2_VP$Group == '1'])),
                             mean.e = c(mean(study1_VP$offline_VP[study1_VP$Group == '1']), mean(study2_VP$offline_VP[study2_VP$Group == '1'])),
                             sd.e = c(sd(study1_VP$offline_VP[study1_VP$Group == '1']), sd(study2_VP$offline_VP[study2_VP$Group == '1'])),
                             n.c = c(length(study1_VP$offline_VP[study1_VP$Group == '0']), length(study2_VP$offline_VP[study2_VP$Group == '0'])),
                             mean.c = c(mean(study1_VP$offline_VP[study1_VP$Group == '0']), mean(study2_VP$offline_VP[study2_VP$Group == '0'])),
                             sd.c = c(sd(study1_VP$offline_VP[study1_VP$Group == '0']), sd(study2_VP$offline_VP[study2_VP$Group == '0'])),
                             studlab = c("Study 1", "Study 2")
)

m.cont_VP_off <- metacont(n.e = n.e,
                          mean.e = mean.e,
                          sd.e = sd.e,
                          n.c = n.c,
                          mean.c = mean.c,
                          sd.c = sd.c,
                          studlab = studlab,
                          data = metadat_VP_off,
                          sm = "SMD",
                          method.smd = "Hedges",
                          comb.fixed = T,
                          comb.random = F,
                          method.tau = "REML",
                          hakn = TRUE,
                          title = "Offline VP")

summary(m.cont_VP_off)

#png(file = "meta_visuomotor_perf_off.png", width = 3200, height = 2000, res = 300)

forest.meta(m.cont_VP_off,
            label.e = "Higher AQ/ ASD",
            label.c = "Lower AQ/ NTP",
            comb.common = T,
            text.common = "Fixed-effect model",
            print.I2.ci = T,
            print.tau2.ci = T,
            print.Q = T,
            print.pval.Q = T,
            test.overall = T,
            details = T
            )

dev.off()
```
