---
title: "Latent Class Analysis"
author: "Cintia Anna Nagy"
date: "2024-08-18"
output: html_document
---
# import packages

```{r message=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(psych)
library(plotrix)
library(lcmm)
library(nnet)
library(questionr)
set.seed(500)
```

# import data

```{r message=FALSE}
study1_SL <- read_csv("processed_data/study_1/data_study_1_SL_offline_online.csv")
study1_VP <- read_csv("processed_data/study_1/data_study_1_VP_offline_online.csv")
```

# Staistical learning
## preprocessing

```{r}
study1_SL$ID <- seq.int(nrow(study1_SL))

study1_SL_numeric <- study1_SL %>% 
  select(c('AQ_total', 'block2_offline','block3_offline', 'block4_offline','block5_offline', 'block6_offline','block7_offline', 'block8_offline','block9_offline', 'block10_offline',
                                       'block11_offline', 'block12_offline','block13_offline', 'block14_offline','block15_offline', 'block16_offline', 'block17_offline','block18_offline', 'block19_offline','block20_offline', 'block21_offline', 'block22_offline','block23_offline', 'block24_offline','block25_offline'))

# test normality
sapply(study1_SL_numeric, shapiro.test)

# make long data
study1_SL_long <- study1_SL %>% 
  select(c( 'ID', 'Group', 'AQ_total', 'Subject', 'block2_offline','block3_offline', 'block4_offline','block5_offline', 'block6_offline','block7_offline', 'block8_offline','block9_offline', 'block10_offline',
                                       'block11_offline', 'block12_offline','block13_offline', 'block14_offline','block15_offline', 'block16_offline', 'block17_offline','block18_offline', 'block19_offline','block20_offline', 'block21_offline', 'block22_offline','block23_offline', 'block24_offline','block25_offline'))

blocks <- c('block2','block3', 'block4','block5', 'block6','block7', 'block8','block9', 'block10',
               'block11', 'block12','block13', 'block14','block15', 'block16', 'block17','block18',
               'block19','block20', 'block21', 'block22','block23', 'block24','block25')

study1_SL_long <- pivot_longer(
  data = study1_SL_long,
  cols = starts_with(blocks),
  names_to = c("Block"),
  values_to = "SL_score"
)

study1_SL_long <- study1_SL_long %>% 
  mutate(Block = gsub('_offline', "", Block)) %>% 
  mutate(Block = gsub('block', "", Block))

study1_SL_long <- study1_SL_long %>% 
  mutate(Block = as.numeric(Block)) %>% 
  mutate(Epoch = case_when(
        between(Block, 2, 5)   ~ 1,
        between(Block, 6, 10)  ~ 2,
        between(Block, 11, 15) ~ 3,
        between(Block, 16, 20) ~ 4,
        between(Block, 21, 25) ~ 5
        ))

study1_SL_wide <- study1_SL_long %>% 
  group_by(ID, Subject, Group, AQ_total, Epoch) %>% 
  summarise(SL_score_epoch = median(SL_score, SL_score, na.rm = T)) %>% 
  ungroup()
```

## fit LCA models

```{r}
m1.lin <- hlme(SL_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_SL_wide)
```

```{r}
m2.lin <- gridsearch(hlme(SL_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_SL_wide, ng = 2, mixture = ~Epoch), rep = 200, maxiter = 50, minit = m1.lin)
```

```{r}
m3.lin <- gridsearch(hlme(SL_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_SL_wide, ng = 3, mixture = ~Epoch), rep = 200, maxiter = 50, minit = m1.lin)
```

## compare fit

```{r}
summarytable(m1.lin, m2.lin, m3.lin, which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "ICL", "%class"))
```

# Visuomotor performance
## preprocessing

```{r}
study1_VP$ID <- seq.int(nrow(study1_VP))

study1_VP_numeric <- study1_VP %>% 
  select(c('AQ_total', 'block2_offline','block3_offline', 'block4_offline','block5_offline', 'block6_offline','block7_offline', 'block8_offline','block9_offline', 'block10_offline',
                                       'block11_offline', 'block12_offline','block13_offline', 'block14_offline','block15_offline', 'block16_offline', 'block17_offline','block18_offline', 'block19_offline','block20_offline', 'block21_offline', 'block22_offline','block23_offline', 'block24_offline','block25_offline'))

# test normality
sapply(study1_VP_numeric, shapiro.test)

# make long data
study1_VP_long <- study1_VP %>% 
  select(c( 'ID', 'Group', 'AQ_total', 'Subject', 'block2_offline','block3_offline', 'block4_offline','block5_offline', 'block6_offline','block7_offline', 'block8_offline','block9_offline', 'block10_offline',
                                       'block11_offline', 'block12_offline','block13_offline', 'block14_offline','block15_offline', 'block16_offline', 'block17_offline','block18_offline', 'block19_offline','block20_offline', 'block21_offline', 'block22_offline','block23_offline', 'block24_offline','block25_offline'))

blocks <- c('block2','block3', 'block4','block5', 'block6','block7', 'block8','block9', 'block10',
               'block11', 'block12','block13', 'block14','block15', 'block16', 'block17','block18',
               'block19','block20', 'block21', 'block22','block23', 'block24','block25')

study1_VP_long <- pivot_longer(
  data = study1_VP_long,
  cols = starts_with(blocks),
  names_to = c("Block"),
  values_to = "VP_score"
)

study1_VP_long <- study1_VP_long %>% 
  mutate(Block = gsub('_offline', "", Block)) %>% 
  mutate(Block = gsub('block', "", Block))

study1_VP_long <- study1_VP_long %>% 
  mutate(Block = as.numeric(Block)) %>% 
  mutate(Epoch = case_when(
        between(Block, 2, 5)   ~ 1,
        between(Block, 6, 10)  ~ 2,
        between(Block, 11, 15) ~ 3,
        between(Block, 16, 20) ~ 4,
        between(Block, 21, 25) ~ 5
        ))

study1_VP_wide <- study1_VP_long %>% 
  group_by(ID, Subject, Group, AQ_total, Epoch) %>% 
  summarise(VP_score_epoch = median(VP_score, VP_score, na.rm = T)) %>% 
  ungroup()
```

## fit LCA models

```{r}
m1.lin <- hlme(VP_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_VP_wide)
```

```{r}
m2.lin <- gridsearch(hlme(VP_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_VP_wide, ng = 2, mixture = ~Epoch), rep = 200, maxiter = 50, minit = m1.lin)
```

```{r}
m3.lin <- gridsearch(hlme(VP_score_epoch ~ Epoch, random = ~Epoch, subject = 'ID', data = study1_VP_wide, ng = 3, mixture = ~Epoch), rep = 200, maxiter = 50, minit = m1.lin)
```

## compare fit

```{r}
summarytable(m1.lin, m2.lin, m3.lin, which = c("G", "loglik", "conv", "npm", "AIC", "BIC", "SABIC", "entropy", "ICL", "%class"))
```

## summarize model

```{r}
summarytable(m1.lin)

#post.prob <- postprob(m1.lin)
```